### ISSUE TITLE
PATCH seems to cause promise errors

### ISSUE THREAD

**Issue by geoidesic** [mrichar1/jsonapi-vuex#151]
I'm able to successfully execute a PATCH request (i.e. the remote store and vuex store seems to update), however I get the following warnings in console:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Cannot delete reactive property on undefined, null, or primitive value: undefined
warn @ vue.runtime.esm.js?2b0e:619
del @ vue.runtime.esm.js?2b0e:1104
deleteRecord @ mutations.js?085d:25
wrappedMutationHandler @ vuex.esm.js?2f62:740
commitIterator @ vuex.esm.js?2f62:392
eval @ vuex.esm.js?2f62:391
_withCommit @ vuex.esm.js?2f62:522
commit @ vuex.esm.js?2f62:390
boundCommit @ vuex.esm.js?2f62:335
local.commit @ vuex.esm.js?2f62:692
eval @ actions.js?4386:217
Promise.then (async)
patch @ actions.js?4386:213
wrappedActionHandler @ vuex.esm.js?2f62:747
dispatch @ vuex.esm.js?2f62:438
boundDispatch @ vuex.esm.js?2f62:332
_callee$ @ jvx.js?3661:28
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
send @ jvx.js?3661:28
_callee2$ @ actions.js?787a:211
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
processQueuedMessage @ actions.js?787a:211
wrappedActionHandler @ vuex.esm.js?2f62:747
dispatch @ vuex.esm.js?2f62:438
boundDispatch @ vuex.esm.js?2f62:332
_callee16$ @ index.js?365c:428
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
processQ @ index.js?365c:387
invokeFunc @ lodash.js?2ef0:10333
trailingEdge @ lodash.js?2ef0:10382
timerExpired @ lodash.js?2ef0:10370
setTimeout (async)
setTimeout @ lodash.js?2ef0:6646
timerExpired @ lodash.js?2ef0:10373
setTimeout (async)
setTimeout @ lodash.js?2ef0:6646
leadingEdge @ lodash.js?2ef0:10341
debounced @ lodash.js?2ef0:10410
_callee$ @ index.js?365c:81
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
wrap @ index.js?365c:81
_callee8$ @ index.js?365c:258
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?fa84:15
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
PATCH @ index.js?365c:258
_callee$ @ index.js?365c:81
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
wrap @ index.js?365c:81
_callee3$ @ index.js?1b62:63
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?fa84:5
_next @ asyncToGenerator.js?fa84:27
eval @ asyncToGenerator.js?fa84:34
F @ _export.js?63b6:36
eval @ asyncToGenerator.js?fa84:23
eval @ index.js?1b62:52
Promise.then (async)
saveData @ index.js?1b62:52
submit @ Settings.vue?ac6d:23
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
Vue.<computed> @ backend.js:1793
eval @ QForm.js?0378:117
Promise.then (async)
submit @ QForm.js?0378:114
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
Show 14 more frames
vue.runtime.esm.js?2b0e:1110 Uncaught (in promise) TypeError: Cannot read property '__ob__' of undefined
    at Function.del [as delete] (vue.runtime.esm.js?2b0e:1110)
    at Store.deleteRecord (mutations.js?085d:25)
    at wrappedMutationHandler (vuex.esm.js?2f62:740)
    at commitIterator (vuex.esm.js?2f62:392)
    at Array.forEach (<anonymous>)
    at eval (vuex.esm.js?2f62:391)
    at Store._withCommit (vuex.esm.js?2f62:522)
    at Store.commit (vuex.esm.js?2f62:390)
    at Store.boundCommit [as commit] (vuex.esm.js?2f62:335)
    at Object.local.commit (vuex.esm.js?2f62:692)
```

**Comment by mrichar1** [comment]
Was this patch against an object in the API that hadn't been previously fetched into the store with a `get` action dispatch? 

It looks like the patch code always tries to delete the item from the store before updating it - if it isn't in the store it would throw an error like this.

I'll fix this up next week so that it only deletes if it exists.

**Comment by geoidesic** [comment]
As far as I can tell, no. It's an object that already exists in the store and is being updated without and changes being present in the data (because jv uses objects as iterators, which breaks front-end libraries that prefer arrays, thus requiring a conversion to an array and thus breaking any ability to compare changes).

**Comment by mrichar1** [comment]
That's interesting - if you could provide the pre-patch store state, patch object and post-patch state, I can dig further.

**Comment by geoidesic** [comment]
When I'm stepping through the code, this error seems to occur even before the PATCH request's response it updated in the inspector. I.e. I can see the PATCH request in listed on the Network tab, but the response tab for that request is blank at the point where this error occurs:
```
TypeError: Cannot read property '__ob__' of undefined
    at Function.del [as delete] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1111:21)
    at Store.deleteRecord (webpack-internal:///./node_modules/jsonapi-vuex/src/mutations.js:52:57)
    at wrappedMutationHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:793:13)
    at commitIterator (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:415:7)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:414:11)
    at Store._withCommit (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:573:3)
    at Store.commit (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:413:8)
    at Store.boundCommit [as commit] (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:358:19)
    at Object.local.commit (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:745:13)
```  
Here's the pre-patch store state:
```
{
  "1": {
    "_jv": {
      "id": "1",
      "isAttr": {
        "_custom": {
          "display": "<span>ƒ</span> isAttr(name)",
          "type": "function"
        }
      },
      "isRel": {
        "_custom": {
          "display": "<span>ƒ</span> isRel(name)",
          "type": "function"
        }
      },
      "links": {
        "self": "/api/bank-details/1"
      },
      "type": "bank_details"
    },
    "account_name": "Company Limited",
    "account_number": 23423234,
    "bank_name": "HSBC",
    "created": "2020-07-17T15:27:14+00:00",
    "modified": "2020-07-14T13:15:36+00:00",
    "sort_code": 23456
  },
  "2": {
    "_jv": {
      "id": "2",
      "isAttr": {
        "_custom": {
          "display": "<span>ƒ</span> isAttr(name)",
          "type": "function"
        }
      },
      "isRel": {
        "_custom": {
          "display": "<span>ƒ</span> isRel(name)",
          "type": "function"
        }
      },
      "links": {
        "self": "/api/bank-details/2"
      },
      "type": "bank_details"
    },
    "account_name": "asdf",
    "account_number": 2222222,
    "bank_name": "asdf",
    "created": "2020-07-19T12:42:58+00:00",
    "modified": "2020-07-17T14:27:15+00:00",
    "sort_code": 234234
  }
}
```
This is the patch object from inspector (looks malformed tbh):
```
jvx send: destructure 
{0: "jv/patch", 1: Array(2)}
0: "jv/patch"
1: Array(2)
0:
account_name: "asdf"
account_number: "2222222"
bank_name: "asdf"
created: "2020-07-19 12:42:58"
modified: "2020-07-17T14:27:15+00:00"
sort_code: 234234
_jv: {type: "bank-details", id: "2"}
__proto__: Object
1:
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
__proto__: Object
length: 2
__proto__: Array(0)
__proto__: Object
```
The post-patch state is identical to the pre-patch state.

**Comment by geoidesic** [comment]
I also for the life of me can't figure out why POST and PATCH are going out to `/api/api` whereas GET is going out to `/api`. I'm using precisely the same Axios config for both but for some reason it duplicates a portion of the URL for PATCH and POST.

**Comment by mrichar1** [comment]
Looking at the patch object it appears to be in the correct format as the args for the patch action - an array where the 1st argument is an object containing the patch data, while the 2nd is the (empty) object where axios params etc go.  

However what's odd is that it the data contains many unchanged fields, and the ones that have changed are casts/formatting changes. I'd expect a patch to have only the changed attributes in it, otherwise it's a dangerous 'regression' of potentially changed fields upstream (see the discussions in #148 around this).

If you want to dig further, the best option would be to log the response from the API to the patch request, and also log the value of `record` in the `deleteRecord`mutation, to see what it is failing to delete: https://github.com/mrichar1/jsonapi-vuex/blob/master/src/mutations.js#L20-L26
